version: 0.2

env:
  variables:
    GITHUB_HUB_CLI_VERSION: 2.13.0

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      # Install hub CLI
      - wget https://github.com/github/hub/releases/download/v$GITHUB_HUB_CLI_VERSION/hub-linux-amd64-$GITHUB_HUB_CLI_VERSION.tgz
      - tar -xzvf hub-linux-amd64-$GITHUB_HUB_CLI_VERSION.tgz && sudo mv hub-linux-amd64-$GITHUB_HUB_CLI_VERSION/bin/hub /usr/local/bin

      # Configure git client
      - git config user.name "CodeBuild Integration Test"
      - git config user.email $COMMIT_EMAIL_ADDRESS
      - git config credential.helper "store --file=.git/credentials"
      - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials

      # Run integration tests
      - ./run_integ_test.sh
