on:
  push:
    branches:
      - integ-tests

name: Integration Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print current build ID
      run: |
        echo Integration test run: githubactionsconfigureawscr-hAMhr2qzHnWH:9f88a86e-c782-4c29-b66d-71b79eccd522

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@1436a160af84c3a086a812f98daf457a042274cb
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Test environment is configured with AWS credentials
      run: |
        aws sts get-caller-identity > /dev/null
