on:
  push:
    branches:
      - integ-tests

name: Integration Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print current build ID
      run: |
        echo Integration test run: githubactionsconfigureawscr-hAMhr2qzHnWH:a3d2460a-dcdf-4e31-9cbb-621e9457c7ac

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@db6655e0af1f829d90be54e90332709754ad5f74
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Test environment is configured with AWS credentials
      run: |
        aws sts get-caller-identity --query Arn | grep "user/github-actions-configure-aws-credentials-integ-tests" > /dev/null

    - name: Configure AWS credentials from role
      uses: aws-actions/configure-aws-credentials@db6655e0af1f829d90be54e90332709754ad5f74
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        role-to-assume: github-actions-configure-aws-credentials-integ-tests
        role-duration-seconds: 900
        role-session-name: github-actions-integ-test
        role-external-id: ${{ secrets.INTEG_TEST_ROLE_EXTERNAL_ID }}

    - name: Test environment is configured with AWS credentials from role
      run: |
        aws sts get-caller-identity --query Arn | grep "role/github-actions-configure-aws-credentials-integ-tests"  > /dev/null
